server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_service_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: movie-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.movieservice.dto.kafka.CrawlMovieResultMessage
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
    listener:
      missing-topics-fatal: false

quartz:
  max-retry: 3
  job:
    fetch-popular-movies:
      name: "FetchPopularMovie"
      group: "daily"
      description: "Job starts at 00:05 AM VNT to get popular movies from TMDb"
      cron-expression: "0 24 0 * * ?"
      time-zone: "Asia/Ho_Chi_Minh"
    fetch-metadata-job:
      name: "FetchMetadataJob"
      group: "daily"
      description: "Job starts at 00:30 AM VNT to fetch metadata of movie which doesn't have metadata"
      cron-expression: "0 26 0 * * ?"
      time-zone: "Asia/Ho_Chi_Minh"

config:
  category:
    top: 3
    movies:
      top: 10
  crawl:
    current-year: 2025
    key: MYIBWPKZBWXPR9VK16O8H0OJT9RVS5ZG
  tmdb:
    base-url: https://api.themoviedb.org/3
    token: ${TMDB_TOKEN}
  metadata:
    maxRetry: 3

connector:
  alb:
    url: localhost
  metadata:
    service:
      port: 8083

aws:
  region: ap-southeast-1
  s3:
    bucket: ryan-movie-source-bucket
    presignedurl:
      expire:
        time: 600
  cloudfront:
    distributiondomain: cdn.ryan-healthcare.com
    keypairid: abcd
    privatekeyssmname: /ryan-movie/cloudfront-private-key
